### PR TITLE
Added information about some php extensions

### PR DESCRIPTION
**Pull request by danielgasser**
Added information about some php extensions to be loaded correctly. See the full article here: https://stackoverflow.com/a/26368386/1387233

### CODE REVIEW

**Comment by mlocati** [comment]
Maybe we can only rewrite this existing sentence:

> In order to easily use PHP from other scripts and console windows, I add the C:\Dev\PHP directory to the PATH variable.

Instead of a suggestion, this can be described as mandatory.

**Comment by danielgasser** [comment]
Ok, it sounds less complicated. But it _must_ be the System variables PATH (Not the User variables PATH)
Or we could write:

> In order to easily use PHP from other scripts and console windows, I add the C:\Dev\PHP directory to the User & System PATH variable.

**Comment by mlocati** [comment]
Thank you! I modified a bit the text (merging the new sentence with the one right above).

**Comment by danielgasser** [comment]
You're welcome! Glad I can give back a bit....

**Pull request merged**
